module.exports = {
  GET_ALARM_TIME: 'get-alarm-time',
  GOT_ALARM_TIME: 'got-alarm-time',
  GET_DISARM_STATUS: 'get-disarm-status',
  GOT_DISARM_STATUS: 'got-disarm-status',
  GET_STREAK_DATA: 'get-streak-data',
  GOT_STREAK_DATA: 'got-streak-data',
  GET_USER_DATA: 'get-user-data',
  GOT_USER_DATA: 'got-user-data',
  GET_SOAKED_COUNT: 'get-soaked-count',
  GOT_SOAKED_COUNT: 'got-soaked-count',
  GET_SKIPPED_DATA: 'get-skipped-data',
  GOT_SKIPPED_DATA: 'got-skipped-data',
  POST_DISARM_RECORDS: 'post-disarm-records',
  UPDATE_ALARM_TIME: 'update-alarm-time',
  UPDATED_ALARM_TIME: 'updated-alarmt-time',
  UPDATE_DISARM_STATUS: 'update-disarm-status',
  UPDATED_DISARM_STATUS: 'updated-disarm-status',
  UPDATE_STREAK_DATA: 'update-streak-data',
  UPDATED_STREAK_DATA: 'updated-streak-data',
  UPDATE_USER_DATA: 'update-user-data',
  UPDATED_USER_DATA: 'updated-user-data',
  UPDATE_SOAKED_COUNT: 'update-soaked-data',
  UPDATED_SOAKED_COUNT: 'updated-soaked-count',
  UPDATE_SKIPPED_DATA: 'update-skipped-data',
  UPDATED_SKIPPED_DATA: 'updated-skipped-data',
};
